use_frameworks!

platform :ios, '10.0'

target 'DynamicSideBar_Example' do
  pod 'DynamicSideBar', :path => '../'

  target 'DynamicSideBar_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
